CocoaPods/Molinillo

- lib/molinillo/resolution.rb
This makes `Resolution` warning-clean, which, in turn, would make Bundler warning-clean again.
This particular Ruby warning (`private attribute?`) is questionable (to say the least) and the fix is awful, but being warning-clean means all of the programs and libraries that depend on Molinillo can be warning-clean.
> [Resolution] Make it warning-clean

- CHANGELOG.md
- lib/molinillo/resolution.rb
> Make richer version conflict messages possible

- CHANGELOG.md
- lib/molinillo/dependency_graph.rb
- lib/molinillo/resolution.rb
- spec/dependency_graph_spec.rb
- spec/resolver_spec.rb
> Refactor the DG

- CHANGELOG.md
- lib/molinillo/resolution.rb
- spec/resolver_spec.rb
- spec/spec_helper.rb
---
I'm investigating an issue (https://github.com/berkshelf/solve/issues/57) in the solve library, which is using Molinillo. I was able to add a reproduction case (https://github.com/berkshelf/solve/commit/b84500e80c22e0596b530838f7a7d299f6f9f870) as a RSpec test for solve, which fails with the following:
```
1) Solutions when using the ruby solver repro case?
Failure/Error: activated.vertex_named(name).payload ? 0 : 1,
NoMethodError:
undefined method `payload' for nil:NilClass
```
When I enable Molinillo's debugging and add some printf debugging of my own, what I find is that a requirement is added for a grandchild, but the child later gets swapped. The `#detach_vertex_named` method is recursive, so it removes the grandchild's vertex, but the requirements removal is not recursive, so …
> Remove transitive requirements when swapping children

- CHANGELOG.md
- lib/molinillo/resolution.rb
I don't know if this is the right fix.  I feel like this is a bandaid for DependencyGraph#initialize_copy being slow but it also seems odd that we're calling .dup on already calculated graphs.  I didn't see where we were intentionally modifying the graphs, so it's unclear if .dup is needed.  It seems as though we're calling .dup because the DependencyGraph uses these inputs for the struct's attributes.  
Note, I didn't add a test since it's not a change in functionality but I verified all tests pass locally.  Feel free to 👎  this PR if you have better ideas on how to fix this.  I ultimately don't care about this change, I'd rather Molinillo not do more work than it needs to do.
We pass activated to sort_dependencies and DependencyState.new, both operations
that probably shouldn't be …
> activated dependencies are input to read only operations so don't dup.

- .rubocop.yml
- CHANGELOG.md
- lib/molinillo/delegates/resolution_state.rb
- lib/molinillo/delegates/specification_provider.rb
- lib/molinillo/dependency_graph.rb
- lib/molinillo/dependency_graph/action.rb
- lib/molinillo/dependency_graph/add_edge_no_circular.rb
- lib/molinillo/dependency_graph/add_vertex.rb
- lib/molinillo/dependency_graph/detach_vertex_named.rb
- lib/molinillo/dependency_graph/log.rb
- lib/molinillo/dependency_graph/set_payload.rb
- lib/molinillo/dependency_graph/tag.rb
- lib/molinillo/dependency_graph/vertex.rb
- lib/molinillo/resolution.rb
- lib/molinillo/state.rb
- spec/dependency_graph/log_spec.rb
- spec/dependency_graph_spec.rb
- spec/errors_spec.rb
- spec/resolver_spec.rb
- spec/spec_helper.rb
- spec/spec_helper/index.rb
- spec/spec_helper/specification.rb
- spec/spec_helper/ui.rb
- spec/state_spec.rb
Along with other performance changes made in bundler, this is good for up to a 3x drop in object allocations and a 3x speed up. Probably can optimize further, but I'm just too excited to keep this to myself much longer 🎉 
@alloy @indirect
> Add an oplog to DependencyGraph to avoid copying it

- ARCHITECTURE.md
- CHANGELOG.md
- Gemfile.lock
- lib/molinillo/dependency_graph.rb
- lib/molinillo/errors.rb
- lib/molinillo/resolution.rb
- spec/dependency_graph_spec.rb
- spec/resolver_spec.rb
Some minor tweaks after (unsuccessfully) trying to debug a resolver issue:
- Cut out some needless possibility attempts, in order to gain a modest efficiency improvement
- Bump `pry` so it doesn't display hundreds of deprecation warnings when used
- Rename `node` to `vertex` everywhere. They're synonymous, but using one improves clarity
~~The removed possibilities are the cases where an existing spec has already been activated for a requirement. In this case, there's no need to iterate through that requirement's possibilities - all but the existing spec would be ignored anyway. For the `BundlerIndex`, on the integration test `can resolve when two specs have the same dependencies`, this reduces the number of steps to resolution from 1390 to 798, and the time taken to do the resolution 100 …
> Respect locked dependencies at possibility creation time

- .rubocop.yml
- ARCHITECTURE.md
- CHANGELOG.md
- lib/molinillo/resolution.rb
If a previous conflict, for a different dependency, is the reason we ended up with the current conflict, then unwinding to a state that would not have caused that conflict could prevent the current one, too.
Makes https://github.com/CocoaPods/Resolver-Integration-Specs/pull/13 pass.
> Consider previous conflicts when determining the state to unwind to

- lib/molinillo/resolution.rb
This speeds up resolution a tad, but makes the conceptual state space a bit simpler.
> Enforce that there is only a single state per requirement

- CHANGELOG.md
- lib/molinillo/resolution.rb
Updates #63 for recent changes to master. Pulls in @iangreenleaf's commit for attributtion.
Closes #63.
> Only raise CircularDependency errors if they prevent resolution

- lib/molinillo/resolution.rb
This is the speedup from #73, applied on its own. The idea behind it is to filter out any "grandparent+" unwinds that have no chance of successful resolution if used.
This PR doesn't speed up the current specs, since none of them currently unwind to grandparent requirements that would be affected, but it doesn't slow them down either. Where the speed up is really noticeable is in #73, where we keep unused unwind options around for later use - in that case, grandparent+ unwinds have a big impact on performance since they are used much more often.
> Filter grandparents and up of requirements when unwinding

- ARCHITECTURE.md
- CHANGELOG.md
- lib/molinillo/delegates/resolution_state.rb
- lib/molinillo/resolution.rb
- lib/molinillo/state.rb
- spec/resolver_spec.rb
- spec/spec_helper/index.rb
- spec/state_spec.rb
Gets Molinillo to the point where it can resolve anything that's thrown at it. Includes the following fixes and speedups (which will be pulled out into separate PRs when they're ready):
- ~~Handling failures where an unwind of a previous conflict  is needed~~ (#72)
- ~~Speeding up resolution by filtering grandparent+ states~~ (#77)
- ~~Handling circular dependencies~~ (#78)
- Handling unwinds of a previous conflict *for the same dependency* is needed (this PR)
TODO:
> Re-enable all the indexes / specs

- CHANGELOG.md
- lib/molinillo/resolution.rb
Fixes https://travis-ci.org/bundler/bundler/jobs/258222644 (from https://github.com/bundler/bundler/pull/5902).
This is basically a short-circuit, so that when searching for different deps yields the same possibility, it's OK that dependencies can be added.
> Allow deps to change for the same possibility

- ARCHITECTURE.md
- CHANGELOG.md
- lib/molinillo/resolution.rb
Insist each PossibilitySet contains contiguous versions. Fixes a potential regression where an older dependency version with identical sub-dependencies to the latest version may be preferred over the second-latest version.
(The above regression is pretty damn unlikely, but this makes the grouping logic theoretically robust, which is nice. And it's not going to slow anything down - non-contiguous groups would only be formed by pretty weird dependency maintainer behaviour.)
Test at https://github.com/CocoaPods/Resolver-Integration-Specs/pull/15.
> Ensure possibility sets only contain contiguous versions

- CHANGELOG.md
- lib/molinillo/resolution.rb
If several previous conflicts would have unwound to the state we eventually unwind to, we shouldn't filter out the versions that would have fixed those previous conflicts.
> Handle case of multiple previous primary unwinds to the same state

- spec/spec_helper/index.rb
Keeps Bundler index in-line with https://github.com/bundler/bundler/pull/6128. New spec will live in Bundler (since this is Bundler-specific).
> Prioritise explicitly requested gems in Bundler dependency sort order

- CHANGELOG.md
- lib/molinillo/dependency_graph/vertex.rb
- lib/molinillo/resolution.rb
Reduces memory usage during resolution. Part of the solution to https://github.com/bundler/bundler/issues/6114.
We're never interested in the size of a vertex's `requirements` array - only in its unique elements. As such, I don't see any reason not to`uniq` it at source.
Previously, we were `uniq`-ing the array in one of the places it was used, but not the other (`Molinillo::Resolver::Resolution#requirement_trees`). As a result, we were creating `Conflict` objects with `requirement_trees` arrays that contained duplicates. Doing so adversely affected memory usage during resolution.
> Make `Vertex#requirements` array unique

- Gemfile.lock
- lib/molinillo/dependency_graph/vertex.rb
This avoids object allocations and also will ensure we don't go over the same node twice
> [Vertex] Speed up recursive methods by manually descending

- molinillo.gemspec
Whilst it's a little odd to specify such a low required Ruby version, doing so will mean Dependabot doesn't try to update gems to versions that aren't compatible with that version.
> Add required_ruby_version to gemspec

- .travis.yml
- spec/resolver_spec.rb
Fixes the build the lazy way. Longer term we should consider having a build matrix (but it's Monday morning and I'm swamped).
(Currently older rubies are failing because they're attempting to install Rubygems 3.0.2, which doesn't support them.)
> Use rubygems 2.7.8 on Travis

- lib/molinillo/compatibility.rb
- lib/molinillo/dependency_graph.rb
- lib/molinillo/dependency_graph/tag.rb
- lib/molinillo/resolution.rb
This PR adds a few YARD annotations to reduce the amount of warnings output when generating documentation (and also, to fix some references).
This does not take care of _all_ the warnings output, but it's an improvement.
This screenshot shows how `Tag` now works, again, because it has the same names of arguments as `Action` (the docstrings of which are used by `(see ...)` reference).
> Add YARD docstring annotations

- CHANGELOG.md
- Gemfile.lock
- lib/molinillo/dependency_graph.rb
- spec/resolver_spec.rb
This will help make resolving those circular dependency errors easier for end users.
> Include full path in CircularDependencyError

- Gemfile.lock
- lib/molinillo.rb
- lib/molinillo/dependency_graph.rb
- lib/molinillo/dependency_graph/add_edge_no_circular.rb
- lib/molinillo/dependency_graph/add_vertex.rb
- lib/molinillo/dependency_graph/delete_edge.rb
- lib/molinillo/dependency_graph/detach_vertex_named.rb
- lib/molinillo/dependency_graph/log.rb
- lib/molinillo/dependency_graph/set_payload.rb
- lib/molinillo/dependency_graph/tag.rb
- lib/molinillo/errors.rb
- lib/molinillo/resolution.rb
- lib/molinillo/resolver.rb
- molinillo.gemspec
As I explained in #127, now that molinillo supports MRI >= 2.0 only, I'd like to use `require_relative` for internal requires.
> Prefer `require_relative` to `require` for internal requires

- .travis.yml
- lib/molinillo/resolution.rb
At 1.8.7 times, `Array.select!` didn't exist. Now it does.
> Simplify 1.8.7 compatibility code

- .travis.yml
This PR updates the CI matrix.
- Updates Ruby patch versions
- Adds Ruby 2.5 to the matrix.
- Removes an old setting from Travis. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Still green! 🟢
> CI: Update patch versions of Ruby, add Ruby 2.5

- CHANGELOG.md
- lib/molinillo/resolution.rb
This is a hot code path during resolution and `Array#-` performs much better than `Array#&`.
With the following sample `Gemfile`:
```ruby
source 'https://rubygems.org'
gem "actionmailer"
gem "mongoid", ">= 0.10.2"
```
It reduces `bundle lock` time from 9.5s to 2.8s on my machine.
All credit to @lukaso for this improvement!
> Use `Array#-` in unwind logic

- lib/molinillo/dependency_graph/vertex.rb
- lib/molinillo/errors.rb
iff means if and only if, but readers without that knowledge might
assume this to be a spelling mistake. To me, this seems like
exclusionary language that is unnecessary. Simply using "if and only if"
or "whether" should suffice.
See https://github.com/ruby/ruby/pull/4035, https://github.com/rubygems/rubygems/pull/4311
I submitted a patch to Ruby to reword this potentially confusing wording. It turns out Rubygems vendors this gem and `iff` exists in this codebase as well. I propose it be changed here as well.
> Replace "iff" with "whether" and "if and only if"

- lib/molinillo/errors.rb
Molinillo provides this proc to customize how requirements are printed, but was not respecting it.
> Use `printable_requirement` proc to print requirements

- CHANGELOG.md
- lib/molinillo/delegates/specification_provider.rb
- lib/molinillo/modules/specification_provider.rb
- lib/molinillo/resolution.rb
Bundler uses `DepProxy` instances as dependencies which are made of an underlying actual dependency and a platform.
However, during resolution only the actual dependency is relevant regarding dependency grouping, so by customizing this method like this
```ruby
dependencies.map(&:dep) == other_dependencies.map(&:dep)
```
we get a more efficient resolution since all spec groups with the same dependencies are properly grouped together.
For example, the Gemfile in [this ticket](https://github.com/rubygems/rubygems/issues/3788) is now resolved very fast.
> Allow customization of dependency comparison

- .github/workflows/test.yml
Rubygems 3.1.3 is not supported by latest version of Ruby.
> Fix CI with latest ruby-head

- lib/molinillo/errors.rb
Currently bundler needs to passed 7 different procs as options, and the logic is split between those procs and molinillo's internals which makes it really hard to follow.
In addition to that, the above is not even enough for our needs. We have some "metadata dependencies" (the running Ruby and RubyGems version), which are not set in the dependency manifest (Gemfile), so we need to customize the message so that it does not read "In Gemfile:". However, that part is not currently customizable.
This commit adds a new proc that allows customizing building the full error message.
> Allow fully customizing molinillo's error building
